// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestUpdateDeleteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testUpdateDelete() {
    driver.get("http://localhost:4200/view-student");
    driver.manage().window().setSize(new Dimension(550, 700));
    driver.findElement(By.cssSelector(".odd:nth-child(1) .btn-info")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("BOsko");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.cssSelector(".even:nth-child(4) .btn-info")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.cssSelector(".even:nth-child(4) .btn-info")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > h4")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(5) .btn-info")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("Jovana");
    driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).sendKeys("jovana@gmail.com");
    driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control"));
      dropdown.findElement(By.xpath("//option[. = 'BCA']")).click();
    }
    driver.findElement(By.cssSelector(".form-control > option:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.cssSelector(".even:nth-child(2) .btn-primary")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .fa")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn-primary")).click();
    driver.findElement(By.cssSelector(".sorting:nth-child(4)")).click();
    js.executeScript("window.scrollTo(0,25)");
    driver.findElement(By.cssSelector(".odd:nth-child(1) .btn-primary")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    driver.findElement(By.cssSelector(".even:nth-child(2) .fa")).click();
    driver.findElement(By.cssSelector(".even:nth-child(2) .btn-primary")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(3) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".even:nth-child(4) .fa")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(3) .fa")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(3) .fa")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".odd:nth-child(3) .fa"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".odd:nth-child(5) .fa")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(1) > td:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_desc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".sorting:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_asc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_asc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".odd:nth-child(1) .fa")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(1) .fa")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".odd:nth-child(1) .fa"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("View Student")).click();
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.linkText("View Student")).click();
    driver.findElement(By.cssSelector(".odd .fa")).click();
    driver.findElement(By.cssSelector(".sorting:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".sorting:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_desc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".sorting:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_asc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".odd .btn-primary")).click();
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.linkText("View Student")).click();
    driver.findElement(By.cssSelector(".sorting:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_desc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".fa")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_desc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_asc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
  }
}
