// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createTest() {
    driver.get("http://localhost:4200/view-student");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("52%#$^SSA");
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("52%#$^11");
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("bosko@gmail.com");
    driver.findElement(By.cssSelector(".ng-untouched")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".ng-untouched"));
      dropdown.findElement(By.xpath("//option[. = 'B-Tech']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("bosko@gmail.com");
    driver.findElement(By.cssSelector(".ng-invalid:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".ng-invalid:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".ng-pristine")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control"));
      dropdown.findElement(By.xpath("//option[. = 'B-Tech']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".ng-dirty:nth-child(2)")).sendKeys("Bosko");
    driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).sendKeys("testnimejl");
    driver.findElement(By.cssSelector(".ng-untouched")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".ng-untouched"));
      dropdown.findElement(By.xpath("//option[. = 'B-Tech']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).sendKeys("testniEMejl");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("View Student")).click();
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".ng-dirty:nth-child(2)")).sendKeys("Bosko");
    driver.findElement(By.cssSelector(".ng-untouched")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".ng-untouched"));
      dropdown.findElement(By.xpath("//option[. = 'MCA']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".ng-dirty:nth-child(2)")).sendKeys("Bosko");
    driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).sendKeys("bosko");
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("TestBranch");
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("testBranch@gmail.com");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".navbar")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".ng-valid")).click();
    driver.findElement(By.cssSelector(".ng-valid")).click();
    driver.findElement(By.cssSelector(".ng-valid")).click();
    driver.findElement(By.cssSelector(".ng-valid")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".ng-valid")).click();
    driver.findElement(By.cssSelector(".ng-valid")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".ng-dirty:nth-child(2)")).sendKeys("Bosko");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("View Student")).click();
    driver.findElement(By.cssSelector(".even:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".even:nth-child(4) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".even:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".even:nth-child(4) > td:nth-child(2)")).click();
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".ng-dirty:nth-child(2)")).sendKeys("Dejan");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("DataTables_Table_10_length")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DataTables_Table_10_length"));
      dropdown.findElement(By.xpath("//option[. = '16']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.name("DataTables_Table_10_length")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DataTables_Table_10_length"));
      dropdown.findElement(By.xpath("//option[. = '20']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    driver.findElement(By.name("DataTables_Table_10_length")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DataTables_Table_10_length"));
      dropdown.findElement(By.xpath("//option[. = 'All']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(4)")).click();
    driver.findElement(By.linkText("View Student")).click();
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".ng-dirty:nth-child(2)")).sendKeys("Darko");
    driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("darko@gmail.com");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("View Student")).click();
    {
      WebElement element = driver.findElement(By.linkText("View Student"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("DataTables_Table_11_wrapper")).click();
    driver.findElement(By.id("DataTables_Table_11_wrapper")).click();
    driver.findElement(By.id("DataTables_Table_11_wrapper")).click();
    driver.findElement(By.id("DataTables_Table_11_info")).click();
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.linkText("1")).click();
    {
      WebElement element = driver.findElement(By.linkText("1"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
  }
}
